param(
    [string]$BaseUrl = "http://127.0.0.1:8000",
    [Parameter(Mandatory = $true)][string]$Email,
    [Parameter(Mandatory = $true)][string]$Password,
    [int]$ProjectId = 1,
    [int]$MilestoneId = 1,
    [int]$Days = 30
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "\n==> $Message" -ForegroundColor Cyan
}

function Assert-HasProperty {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$PropertyName,
        [Parameter(Mandatory = $true)][string]$Context
    )

    if (-not ($Object.PSObject.Properties.Name -contains $PropertyName)) {
        throw "$Context missing expected property: $PropertyName"
    }
}

try {
    Write-Step "Logging in to get JWT token"
    $loginBody = @{
        email = $Email
        password = $Password
    } | ConvertTo-Json

    $loginResponse = Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/auth/login" -ContentType "application/json" -Body $loginBody
    Assert-HasProperty -Object $loginResponse -PropertyName "token" -Context "Login response"

    $token = $loginResponse.token
    if ([string]::IsNullOrWhiteSpace($token)) {
        throw "Login succeeded but token is empty."
    }

    $headers = @{ Authorization = "Bearer $token" }

    Write-Step "Testing GET /api/projects/$ProjectId/risk/forecast"
    $riskUrl = "$BaseUrl/api/projects/$ProjectId/risk/forecast?days=$Days"
    $riskResponse = Invoke-RestMethod -Method Get -Uri $riskUrl -Headers $headers

    Assert-HasProperty -Object $riskResponse -PropertyName "risk_score" -Context "Risk forecast response"
    Assert-HasProperty -Object $riskResponse -PropertyName "risk_level" -Context "Risk forecast response"
    Assert-HasProperty -Object $riskResponse -PropertyName "signals" -Context "Risk forecast response"

    Write-Host "PASS: Risk forecast API" -ForegroundColor Green
    Write-Host ("risk_score={0}, risk_level={1}" -f $riskResponse.risk_score, $riskResponse.risk_level)

    Write-Step "Testing POST /api/projects/$ProjectId/milestones/$MilestoneId/calendar-sync"
    $calendarBody = @{
        provider = "google_calendar"
        title = "Local Test Milestone Sync"
        description = "Generated by scripts/test_project_intelligence_apis.ps1"
        timezone = "Africa/Tunis"
        attendees = @($Email)
        dry_run = $true
    } | ConvertTo-Json -Depth 5

    $calendarUrl = "$BaseUrl/api/projects/$ProjectId/milestones/$MilestoneId/calendar-sync"
    $calendarResponse = Invoke-RestMethod -Method Post -Uri $calendarUrl -Headers $headers -ContentType "application/json" -Body $calendarBody

    Assert-HasProperty -Object $calendarResponse -PropertyName "sync_status" -Context "Calendar sync response"
    Assert-HasProperty -Object $calendarResponse -PropertyName "event_payload" -Context "Calendar sync response"

    Write-Host "PASS: Calendar sync API" -ForegroundColor Green
    Write-Host ("sync_status={0}" -f $calendarResponse.sync_status)

    Write-Host "\nAll local project intelligence API tests passed." -ForegroundColor Green
}
catch {
    Write-Host "\nFAIL: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Tip: verify server is running and credentials/project permissions are valid." -ForegroundColor Yellow
    exit 1
}
